### ISSUE TITLE
onRequestDismiss its not work

### ISSUE THREAD

**Issue by arafat813** [paufau/react-native-multiple-modals#10]
`
export const BlockingModal: FC<BlockingModalProps> = ({
  onSubmit,
}) => {
  const [isVisible, setVisibility] = useState(true);

  const hide = () => {
    setVisibility(false);
    setTimeout(onSubmit, 500);
  };

  return (
    <ModalView
      contentContainerStyle={styles.contentContainer}
      onRequestDismiss={(val)=>{console.log(val)}}
      renderBackdrop={() =>
        isVisible ? (
          <Animated.View
            entering={FadeIn}
            exiting={FadeOut}
            style={styles.backdrop}
          />
        ) : null
      }>
      {isVisible ? (
        <SafeAreaView
          edges={Platform.select({android: ['bottom', 'top'], ios: []})}>
          <Animated.View
            entering={SlideInDown}
            exiting={SlideOutDown}
            style={styles.modal}>
            <Text style={styles.title}>Some Meaningful Title</Text>
            <View style={styles.buttons}>
                <Text onPress={hide}>Submit</Text>
            </View>
          </Animated.View>
        </SafeAreaView>
      ) : null}
    </ModalView>
  );
};
`

**Comment by paufau** [comment]
Hey @arafat813 seems like it's an expected behavior. 
https://github.com/paufau/react-native-multiple-modals?tab=readme-ov-file#renderbackdrop---reactnode

Try it like this
```typescript
const AnimatedPressable = Animated.createAnimatedComponent(Pressable);

renderBackdrop={() =>
  isVisible ? (
    <AnimatedPressable
        entering={FadeIn}
        exiting={FadeOut}
        style={styles.backdrop}
        onPress={() => console.log('Backdrop pressed')}
    />
) : null}
```

I'm referring to this example
https://github.com/paufau/react-native-multiple-modals-examples/blob/main/demo-components/src/modals/animated/AnimatedModal.tsx

**Comment by arafat813** [comment]
Thank you, it was my oversight.
